version: '3.8'

services:
  bot:
    build: .
    container_name: discord-j4fn-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
